//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!


package com.manicken;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class SelectionDialog extends JPanel {
    public JList<String> lstItems;
    public JCheckBox chkDebugMode;
    public JCheckBox chkRebuildExamplesMenu;
    public JCheckBox chkRebuildLibraryMenu;
    public JLabel lblItemList;

    public SelectionDialog() {
        //construct preComponents

        //construct components
        lstItems = new JList<String> ();
        chkDebugMode = new JCheckBox ("Activate some debug output");
        chkRebuildExamplesMenu = new JCheckBox ("Rebuild Examples Menu");
        chkRebuildLibraryMenu = new JCheckBox ("Rebuild Library Menu");
        lblItemList = new JLabel ("Select items to save (not used yet):");

        //adjust size and set layout
        setPreferredSize (new Dimension (229, 487));
        setLayout (null);

        JScrollPane scrollPane = new JScrollPane();
        scrollPane.setViewportView(lstItems);
        lstItems.setLayoutOrientation(JList.VERTICAL);
        scrollPane.setBounds (5, 115, 220, 370);
        
        //add components
        add (scrollPane);
        add (chkDebugMode);
        add (chkRebuildExamplesMenu);
        add (chkRebuildLibraryMenu);
        add (lblItemList);

        //set component bounds (only needed by Absolute Positioning)
        //lstItems.setBounds (5, 115, 220, 370);
        chkDebugMode.setBounds (0, 5, 195, 25);
        chkRebuildExamplesMenu.setBounds (0, 30, 175, 25);
        chkRebuildLibraryMenu.setBounds (0, 55, 145, 20);
        lblItemList.setBounds (5, 85, 220, 25);

        
    }

}
